swagger: "2.0"
info:
  title: BookInfo API
  description: Получение книги по ID
  version: "1.0"

host: 9ce8-37-99-64-112.ngrok-free.app
basePath: /
schemes:
  - http

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Введите токен в формате **Bearer &lt;ваш токен&gt;**

security:
  - BearerAuth: []

paths:
  /books/{book_id}:
    get:
      summary: Получить книгу по ID
      parameters:
        - name: book_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Успешный ответ
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              author:
                type: string
        404:
          description: Книга не найдена
