site_name: 'book info 2.0'
theme:
  name: 'material'
nav:
  - Описание: index.md
  - Установка: installation.md
  - Books:
      - GET: get/get_books.md
  - Оплата:
      - Проверка: payment/check.md
      - Оплата: payment/confirm.md
      - Подтверждение: payment/notify.md

