site_name: 'book info 2.0'
theme:
  name: 'material'
markdown_extensions:
  - pymdownx.tasklist
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - glightbox
nav:
  - О проекте: index.md
  - Установка: installation.md
  - База данных:
    - Схема: db/schema.md
    - Стартовые скрипты: db/start_db.md
    - CRUD: db/crud.md
  - Авторизация: get_auth.md
  - API:
    - Книги:
      - Получение книг по параметрам запроса: API/books/get_books.md
      - Получение книги по id: API/books/get_books_by_id.md
      - Добавление новой книги: API/books/post_books.md
      - Изменение книги: API/books/put_books.md
      - Удаление книги: API/books/delete_books.md
    - Читатели:
      - Получение читателей по параметрам запроса: API/readers/get_readers.md
      - Добавление нового читателя: API/readers/post_readers.md
      - Изменение читателя: API/readers/put_readers.md
    - Работники:
      - Получение работников по параметрам запроса: API/workers/get_workers.md
      - Изменение работника: API/workers/put_workers.md
    - Писатели:
      - Получение писателей по параметрам запроса: API/writers/get_writers.md
      - Добавление нового писателя: API/writers/post_writers.md
      - Изменение писателя: API/writers/put_writers.md
  - Оплата: payment.md

