site_name: 'book info 2.0'
theme:
  name: 'material'
markdown_extensions:
  - pymdownx.tasklist
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - glightbox
nav:
  - О проекте: index.md
  - Установка: installation.md
  - База данных:
    - Схема: db/schema.md
    - Стартовые скрипты: db/start_db.md
    - CRUD: db/crud.md
  - Авторизация: get_auth.md
  - API:
    - Книги:
      - Получение книг по параметрам запроса: API/get_books.md
      - Получение книги по id: API/get_books_by_id.md
      - Добавление новой книги: API/post_books.md
    - Пользователи:
      - GET: API/get/get_users.md
      - POST: API/post/post_users.md
  - Оплата:
      - Проверка: payment/check.md
      - Оплата: payment/confirm.md
      - Подтверждение: payment/notify.md
